name: CI Pipeline

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  Release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Install dependencies
        run: go get .

      - name: Build Project
        run: go build -o qcpp.exe .

      - name: Run Tests
        run: go test -json ./internal > TestResults-${{ github.ref_name }}.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Quick-Cpp-Results-${{ github.ref_name }}
          path: ./internal/TestResults-${{ github.ref_name }}.json

      - name: Clean up
        run: |
          Remove-Item TestResults-$${{ github.ref_name }}.json
          Remove-Item qcpp.exe
        shell: pwsh

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
